# -*- coding: utf-8 -*-

'''Lấy các thông tin như ảnh, bbox, text từ file pdf'''
"""PDF_to_box_text_img.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wFPGcMmyWLXv-KKFUKDOL3swVLiuAmfH
"""
'''
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/MyDrive/Resumes_Project/preprocess/src/annotation'
!ls

!pip install -r requirements.txt
!apt-get install poppler-utils

"""### Lấy thông tin box, text từ file pdf của"""

!python pdf_bboxes.py --input_pdf "input_path" \
                    --output_dir "output_path"  \
                    --csv_folder "csv/" \
                    --img_folder "img/" \
                    --img_origin "img_origin/"  \
                    --json_folder "json/"



'''

