from __future__ import print_function
from mailmerge import MailMerge 
from datetime import date 


cust1_1 = {
    'city': 'THÀNH PHỐ HÀ NỘI',
    'town': 'THỊ XÃ SƠN TÂY',
    'ward1': 'UBND PHƯỜNG QUANG TRUNG',
    'ward2' : 'Phường Quang Trung',
    'day': '07',
    'month': '05',
    'year': '2021',
    'name': 'BÙI THỊ LIÊN',
    'dob': '20/10/1998',
    'dob_chu': "ngày hai mươi, tháng mười, năm một nghìn chín trăm chín tám",
    'gender': 'Nữ',
    "nation": "Kinh",
    'nationality': "Việt Nam",
    'place_of_birth': 'Phòng khám bệnh thị xã Sơn Tây',
    'hown_town': "",
    'person_id': "",
    'name_mother':"CẨN THỊ HIỀN",
    'yob_mother': "1963",
    'nation_mother': "Kinh",
    'nationality_mother': "Việt Nam",
    'residence_mother': "Khu tập thể cầu đường 3",
    'name_father':"NGUYỄN VĂN MINH",
    'yob_father': "1964",
    'nation_father': "Kinh",
    'nationality_father': "Việt Nam",
    'residence_father': "Đội 7 thôn văn Gia, xã Trung Hưng, Sơn Tây",
    'register_address': "UBND phường Quang Trung, thị xã Sơn Tây, thành phố Hà Nội",
    'number_id': "14",
    'date': "26/01/1991",
    'note': "Thực hiện việc trích lục từ Sổ đăng kí khai sinh/"
}

cust1_2 = {
    'city': 'THÀNH PHỐ HÀ NỘI',
    'town': 'THỊ XÃ SƠN TÂY',
    'ward1': 'UBND PHƯỜNG QUANG TRUNG',
    'ward2' : 'Phường Quang Trung',
    'day': '07',
    'month': '05',
    'year': '2021',
    'name': 'BÙI THỊ LIÊN',
    'dob': '20/10/1998',
    'dob_chu': "ngày hai mươi, tháng mười, năm một nghìn chín trăm chín tám",
    'gender': 'Nữ',
    "nation": "Kinh",
    'nationality': "Việt Nam",
    'place_of_birth': 'Phòng khám bệnh thị xã Sơn Tây',
    'hown_town': "",
    'person_id': "",
    'name_mother':"CẨN THỊ HIỀN",
    'yob_mother': "1963",
    'nation_mother': "Kinh",
    'nationality_mother': "Việt Nam",
    'residence_mother': "Khu tập thể cầu đường 3",
    'name_father':"NGUYỄN VĂN MINH",
    'yob_father': "1964",
    'nation_father': "Kinh",
    'nationality_father': "Việt Nam",
    'residence_father': "Đội 7 thôn văn Gia, xã Trung Hưng, Sơn Tây",
    'register_address': "UBND phường Quang Trung, thị xã Sơn Tây, thành phố Hà Nội",
    'number_id': "14",
    'date': "26/01/1991",
    'note': "Thực hiện việc trích lục từ Sổ đăng kí khai sinh/"
}

cust1_3 = {
    'city': 'THÀNH PHỐ HÀ NỘI',
    'town': 'THỊ XÃ SƠN TÂY',
    'ward1': 'UBND PHƯỜNG QUANG TRUNG',
    'ward2' : 'Phường Quang Trung',
    'day': '07',
    'month': '05',
    'year': '2021',
    'name': 'BÙI THỊ LIÊN',
    'dob': '20/10/1998',
    'dob_chu': "ngày hai mươi, tháng mười, năm một nghìn chín trăm chín tám",
    'gender': 'Nữ',
    "nation": "Kinh",
    'nationality': "Việt Nam",
    'place_of_birth': 'Phòng khám bệnh thị xã Sơn Tây',
    'hown_town': "",
    'person_id': "",
    'name_mother':"",
    'yob_mother': "",
    'nation_mother': "",
    'nationality_mother': "",
    'residence_mother': "",
    'name_father':"NGUYỄN VĂN MINH",
    'yob_father': "1964",
    'nation_father': "Kinh",
    'nationality_father': "Việt Nam",
    'residence_father': "Đội 7 thôn văn Gia, xã Trung Hưng, Sơn Tây",
    'register_address': "UBND phường Quang Trung, thị xã Sơn Tây, thành phố Hà Nội",
    'number_id': "14",
    'date': "26/01/1991",
    'note': "Thực hiện việc trích lục từ Sổ đăng kí khai sinh/"
}

cust1_4 = {
    'city': 'THÀNH PHỐ HÀ NỘI',
    'town': 'THỊ XÃ SƠN TÂY',
    'ward1': 'UBND PHƯỜNG QUANG TRUNG',
    'ward2' : 'Phường Quang Trung',
    'day': '07',
    'month': '05',
    'year': '2021',
    'name': 'BÙI THỊ LIÊN',
    'dob': '20/10/1998',
    'dob_chu': "ngày hai mươi, tháng mười, năm một nghìn chín trăm chín tám",
    'gender': 'Nữ',
    "nation": "Kinh",
    'nationality': "Việt Nam",
    'place_of_birth': 'Phòng khám bệnh thị xã Sơn Tây',
    'hown_town': "",
    'person_id': "",
    'name_mother':"CẨN THỊ HIỀN",
    'yob_mother': "1963",
    'nation_mother': "Kinh",
    'nationality_mother': "Việt Nam",
    'residence_mother': "Khu tập thể cầu đường 3",
    'name_father':"",
    'yob_father': "",
    'nation_father': "",
    'nationality_father': "",
    'residence_father': "Đội 7 thôn văn Gia, xã Trung Hưng, Sơn Tây",
    'register_address': "UBND phường Quang Trung, thị xã Sơn Tây, thành phố Hà Nội",
    'number_id': "14",
    'date': "26/01/1991",
    'note': "Thực hiện việc trích lục từ Sổ đăng kí khai sinh/"
}


cust2_1 = {
    'city': 'THÀNH PHỐ HỒ CHÍ MINH',
    'town': 'QUẬN 2',
    'ward1': 'UBND PHƯỜNG BÌNH TRƯNG TÂY',
    'ward2' : 'Bình Trưng Tây',
    'day': '17',
    'month': '11',
    'year': '2017',
    'name': 'NGUYỄN THỊ TRÀ MY',
    'dob': '08/4/2015',
    'dob_chu': "Ngày, tám, tháng 4, năm hai ngàn không trăm mười lăm",
    'gender': 'Nữ',
    "nation": "Kinh",
    'nationality': "Việt Nam",
    'place_of_birth': 'Bệnh viện Quận 2, thành phố Hồ Chí Minh',
    'hown_town': "Thành phố Hồ Chí Minh",
    'person_id': "079315004644",
    'name_mother':"NGUYỄN THỊ HỒNG NGA",
    'yob_mother': "11/10/1986",
    'nation_mother': "Kinh",
    'nationality_mother': "Việt Nam",
    'residence_mother': "69 đường 31, khu phố 6, phường Bình Trưng Tây, quận 2, thành phố Hồ Chí Minh",
    'name_father':"",
    'yob_father': "",
    'nation_father': "",
    'nationality_father': "",
    'residence_father': "",
    'register_address': "Ủy ban nhân dân phường Bình Trưng Tây, quận 2, thành phố Hồ Chí Minh",
    'number_id': "371",
    'date': "17/11/2017",
    'note': "Thực hiện việc trích lục từ sổ đăng kí khai sinh."
}

cust2_1 = {
    'city': 'THÀNH PHỐ HỒ CHÍ MINH',
    'town': 'QUẬN 2',
    'ward1': 'UBND PHƯỜNG BÌNH TRƯNG TÂY',
    'ward2' : 'Bình Trưng Tây',
    'day': '17',
    'month': '11',
    'year': '2017',
    'name': 'NGUYỄN THỊ TRÀ MY',
    'dob': '08/4/2015',
    'dob_chu': "Ngày, tám, tháng 4, năm hai ngàn không trăm mười lăm",
    'gender': 'Nữ',
    "nation": "Kinh",
    'nationality': "Việt Nam",
    'place_of_birth': 'Bệnh viện Quận 2, thành phố Hồ Chí Minh',
    'hown_town': "Thành phố Hồ Chí Minh",
    'person_id': "079315004644",
    'name_mother':"NGUYỄN THỊ HỒNG NGA",
    'yob_mother': "11/10/1986",
    'nation_mother': "Kinh",
    'nationality_mother': "Việt Nam",
    'residence_mother': "69 đường 31, khu phố 6, phường Bình Trưng Tây, quận 2, thành phố Hồ Chí Minh",
    'name_father':"NGUYỄN VĂN A",
    'yob_father': "10/10/1995",
    'nation_father': "Tày",
    'nationality_father': "Việt Nam",
    'residence_father': "",
    'register_address': "Ủy ban nhân dân phường Bình Trưng Tây, quận 2, thành phố Hồ Chí Minh",
    'number_id': "371",
    'date': "17/11/2017",
    'note': "Thực hiện việc trích lục từ sổ đăng kí khai sinh."
}

cust2_2 = {
    'city': 'THÀNH PHỐ HỒ CHÍ MINH',
    'town': 'QUẬN 2',
    'ward1': 'UBND PHƯỜNG BÌNH TRƯNG TÂY',
    'ward2' : 'Bình Trưng Tây',
    'day': '17',
    'month': '11',
    'year': '2017',
    'name': 'NGUYỄN THỊ TRÀ MY',
    'dob': '08/4/2015',
    'dob_chu': "Ngày, tám, tháng 4, năm hai ngàn không trăm mười lăm",
    'gender': 'Nữ',
    "nation": "Kinh",
    'nationality': "Việt Nam",
    'place_of_birth': 'Bệnh viện Quaajn2, thành phố Hồ Chí Minh',
    'hown_town': "Thành phố Hồ Chí Minh",
    'person_id': "079315004644",
    'name_mother':"NGUYỄN THỊ HỒNG NGA",
    'yob_mother': "11/10/1986",
    'nation_mother': "Kinh",
    'nationality_mother': "Việt Nam",
    'residence_mother': "69 đường 31, khu phố 6, phường Bình Trưng Tây, quận 2, thành phố Hồ Chí Minh",
    'name_father':"NGUYỄN VĂN A",
    'yob_father': "10/10/1995",
    'nation_father': "Tày",
    'nationality_father': "Việt Nam",
    'residence_father': "Hà Nội",
    'register_address': "Ủy ban nhân dân phường Bình Trưng Tây, quận 2, thành phố Hồ Chí Minh",
    'number_id': "371",
    'date': "17/11/2017",
    'note': "Thực hiện việc trích lục từ sổ đăng kí khai sinh."
}


cust2_3 = {
    'city': 'THÀNH PHỐ HỒ CHÍ MINH',
    'town': 'QUẬN 2',
    'ward1': 'UBND PHƯỜNG BÌNH TRƯNG TÂY',
    'ward2' : 'Bình Trưng Tây',
    'day': '17',
    'month': '11',
    'year': '2017',
    'name': 'NGUYỄN THỊ TRÀ MY',
    'dob': '08/4/2015',
    'dob_chu': "Ngày, tám, tháng 4, năm hai ngàn không trăm mười lăm",
    'gender': 'Nữ',
    "nation": "Kinh",
    'nationality': "Việt Nam",
    'place_of_birth': 'Bệnh viện Quận 2, thành phố Hồ Chí Minh',
    'hown_town': "Thành phố Hồ Chí Minh",
    'person_id': "079315004644",
    'name_mother':"",
    'yob_mother': "",
    'nation_mother': "",
    'nationality_mother': "",
    'residence_mother': "69 đường 31, khu phố 6, phường Bình Trưng Tây, quận 2, thành phố Hồ Chí Minh",
    'name_father':"NGUYỄN VĂN A",
    'yob_father': "10/10/1995",
    'nation_father': "Tày",
    'nationality_father': "Việt Nam",
    'residence_father': "",
    'register_address': "Ủy ban nhân dân phường Bình Trưng Tây, quận 2, thành phố Hồ Chí Minh",
    'number_id': "371",
    'date': "17/11/2017",
    'note': "Thực hiện việc trích lục từ sổ đăng kí khai sinh."
}


cust2_4 = {
    'city': 'THÀNH PHỐ HỒ CHÍ MINH',
    'town': 'QUẬN 2',
    'ward1': 'UBND PHƯỜNG BÌNH TRƯNG TÂY',
    'ward2' : 'Bình Trưng Tây',
    'day': '17',
    'month': '11',
    'year': '2017',
    'name': 'NGUYỄN THỊ TRÀ MY',
    'dob': '08/4/2015',
    'dob_chu': "Ngày, tám, tháng 4, năm hai ngàn không trăm mười lăm",
    'gender': 'Nữ',
    "nation": "Kinh",
    'nationality': "Việt Nam",
    'place_of_birth': 'Bệnh viện Quận 2, thành phố Hồ Chí Minh',
    'hown_town': "Thành phố Hồ Chí Minh",
    'person_id': "079315004644",
    'name_mother':"NGUYỄN THỊ HỒNG NGA",
    'yob_mother': "11/10/1986",
    'nation_mother': "Kinh",
    'nationality_mother': "Việt Nam",
    'residence_mother': "69 đường 31, khu phố 6, phường Bình Trưng Tây, quận 2, thành phố Hồ Chí Minh",
    'name_father':"",
    'yob_father': "",
    'nation_father': "",
    'nationality_father': "",
    'residence_father': "",
    'register_address': "Ủy ban nhân dân phường Bình Trưng Tây, quận 2, thành phố Hồ Chí Minh",
    'number_id': "371",
    'date': "17/11/2017",
    'note': "Thực hiện việc trích lục từ sổ đăng kí khai sinh."
}

# gen document từ template

def gen(template, result, cust):
    document = MailMerge(template)
    # print(document.get_merge_fields())

    document.merge(**cust)

    document.write(result)

gen("template1_day_du.docx", "DataGen/template1_1.docx", cust1_1)
gen("template1_day_du.docx", "DataGen/template1_2.docx", cust2_1)
gen("template2_day_du.docx", "DataGen/template2_1.docx", cust1_2)
gen("template2_day_du.docx", "DataGen/template2_2.docx", cust2_2)
gen("template3_thieu_tt_me.docx", "DataGen/template3_1.docx", cust1_3)
gen("template3_thieu_tt_me.docx", "DataGen/template3_2.docx", cust2_3)
gen("template4_thieu_tt_bo.docx", "DataGen/template4_1.docx", cust1_4)
gen("template4_thieu_tt_bo.docx", "DataGen/template4_2.docx", cust2_4)
